import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_content_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_media_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_archive_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_form_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_pages_blocks_dynamic_blog_grid_collection_type" AS ENUM('posts', 'courses');
  CREATE TYPE "public"."enum__pages_v_blocks_content_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum__pages_v_blocks_dynamic_blog_grid_collection_type" AS ENUM('posts', 'courses');
  CREATE TYPE "public"."enum_posts_blocks_content_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_posts_blocks_media_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_posts_blocks_archive_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_posts_blocks_form_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_posts_blocks_dynamic_blog_grid_collection_type" AS ENUM('posts', 'courses');
  CREATE TYPE "public"."enum__posts_v_blocks_content_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum__posts_v_blocks_media_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum__posts_v_blocks_archive_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum__posts_v_blocks_form_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum__posts_v_blocks_dynamic_blog_grid_collection_type" AS ENUM('posts', 'courses');
  CREATE TYPE "public"."enum_courses_blocks_content_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_courses_blocks_media_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_courses_blocks_archive_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_courses_blocks_form_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_courses_blocks_dynamic_blog_grid_collection_type" AS ENUM('posts', 'courses');
  CREATE TYPE "public"."enum__courses_v_blocks_content_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum__courses_v_blocks_media_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum__courses_v_blocks_archive_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum__courses_v_blocks_form_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum__courses_v_blocks_dynamic_blog_grid_collection_type" AS ENUM('posts', 'courses');
  CREATE TYPE "public"."enum_blog_overview_blocks_content_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_blog_overview_blocks_media_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_blog_overview_blocks_archive_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_blog_overview_blocks_form_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_blog_overview_blocks_dynamic_blog_grid_collection_type" AS ENUM('posts', 'courses');
  CREATE TYPE "public"."enum_course_overview_blocks_content_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_course_overview_blocks_media_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_course_overview_blocks_archive_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_course_overview_blocks_form_block_color_scheme" AS ENUM('light', 'dark', 'primary', 'secondary', 'custom');
  CREATE TYPE "public"."enum_course_overview_blocks_dynamic_blog_grid_collection_type" AS ENUM('posts', 'courses');
  ALTER TABLE "pages_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'primary';
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'U gaat akkoord met onze {privacyPolicy} en {termsLink}.';
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "rich_text" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_archive" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_form_block" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "contact_section_contact_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_team" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_team" ALTER COLUMN "hiring_section_hiring_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_testimonials" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_pricing_table" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_two_column_layout" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "header_section_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_header" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_gallery" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_dynamic_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages" ALTER COLUMN "hero_rich_text" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'primary';
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'U gaat akkoord met onze {privacyPolicy} en {termsLink}.';
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "rich_text" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_archive" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_form_block" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "contact_section_contact_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_team" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_team" ALTER COLUMN "hiring_section_hiring_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_testimonials" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_pricing_table" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_two_column_layout" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "header_section_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_header" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_gallery" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v_blocks_dynamic_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_rich_text" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'primary';
  ALTER TABLE "posts_blocks_cta" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'U gaat akkoord met onze {privacyPolicy} en {termsLink}.';
  ALTER TABLE "posts_blocks_content_columns" ALTER COLUMN "rich_text" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_archive" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_form_block" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_faq" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_faq" ALTER COLUMN "contact_section_contact_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_team" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_team" ALTER COLUMN "hiring_section_hiring_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_testimonials" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_pricing_table" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_two_column_layout" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_feature_grid" ALTER COLUMN "header_section_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_header" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_gallery" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "posts_blocks_dynamic_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'primary';
  ALTER TABLE "_posts_v_blocks_cta" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'U gaat akkoord met onze {privacyPolicy} en {termsLink}.';
  ALTER TABLE "_posts_v_blocks_content_columns" ALTER COLUMN "rich_text" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_archive" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_form_block" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_faq" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_faq" ALTER COLUMN "contact_section_contact_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_team" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_team" ALTER COLUMN "hiring_section_hiring_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_testimonials" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_pricing_table" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_two_column_layout" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_feature_grid" ALTER COLUMN "header_section_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_header" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_gallery" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_posts_v_blocks_dynamic_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'primary';
  ALTER TABLE "courses_blocks_cta" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'U gaat akkoord met onze {privacyPolicy} en {termsLink}.';
  ALTER TABLE "courses_blocks_content_columns" ALTER COLUMN "rich_text" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_archive" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_form_block" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_faq" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_faq" ALTER COLUMN "contact_section_contact_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_team" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_team" ALTER COLUMN "hiring_section_hiring_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_testimonials" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_pricing_table" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_two_column_layout" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_feature_grid" ALTER COLUMN "header_section_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_header" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_gallery" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "courses_blocks_dynamic_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'primary';
  ALTER TABLE "_courses_v_blocks_cta" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'U gaat akkoord met onze {privacyPolicy} en {termsLink}.';
  ALTER TABLE "_courses_v_blocks_content_columns" ALTER COLUMN "rich_text" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_archive" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_form_block" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_faq" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_faq" ALTER COLUMN "contact_section_contact_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_team" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_team" ALTER COLUMN "hiring_section_hiring_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_testimonials" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_pricing_table" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_two_column_layout" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_feature_grid" ALTER COLUMN "header_section_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_header" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_gallery" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "_courses_v_blocks_dynamic_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "global_cta" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'primary';
  ALTER TABLE "blog_overview_blocks_cta" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'U gaat akkoord met onze {privacyPolicy} en {termsLink}.';
  ALTER TABLE "blog_overview_blocks_content_columns" ALTER COLUMN "rich_text" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_archive" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_form_block" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_faq" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_faq" ALTER COLUMN "contact_section_contact_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_team" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_team" ALTER COLUMN "hiring_section_hiring_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_testimonials" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_pricing_table" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_two_column_layout" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_feature_grid" ALTER COLUMN "header_section_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_header" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_gallery" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "blog_overview_blocks_dynamic_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'primary';
  ALTER TABLE "course_overview_blocks_cta" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'U gaat akkoord met onze {privacyPolicy} en {termsLink}.';
  ALTER TABLE "course_overview_blocks_content_columns" ALTER COLUMN "rich_text" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_archive" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_form_block" ALTER COLUMN "intro_content" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_faq" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_faq" ALTER COLUMN "contact_section_contact_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_team" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_team" ALTER COLUMN "hiring_section_hiring_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_testimonials" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_pricing_table" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_two_column_layout" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_feature_grid" ALTER COLUMN "header_section_description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_header" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_gallery" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "course_overview_blocks_dynamic_blog_grid" ALTER COLUMN "description" SET DEFAULT '{"root":{"type":"root","format":"","indent":0,"version":1,"children":[{"type":"paragraph","version":1,"children":[]}],"direction":"ltr"}}'::jsonb;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "form_id" integer;
  ALTER TABLE "pages_blocks_content" ADD COLUMN "color_scheme" "enum_pages_blocks_content_color_scheme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "color_scheme" "enum_pages_blocks_media_block_color_scheme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "color_scheme" "enum_pages_blocks_archive_color_scheme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "color_scheme" "enum_pages_blocks_form_block_color_scheme" DEFAULT 'light';
  ALTER TABLE "pages_blocks_dynamic_blog_grid" ADD COLUMN "collection_type" "enum_pages_blocks_dynamic_blog_grid_collection_type" DEFAULT 'posts';
  ALTER TABLE "pages_rels" ADD COLUMN "courses_id" integer;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "form_id" integer;
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "color_scheme" "enum__pages_v_blocks_content_color_scheme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "color_scheme" "enum__pages_v_blocks_media_block_color_scheme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "color_scheme" "enum__pages_v_blocks_archive_color_scheme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "color_scheme" "enum__pages_v_blocks_form_block_color_scheme" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_dynamic_blog_grid" ADD COLUMN "collection_type" "enum__pages_v_blocks_dynamic_blog_grid_collection_type" DEFAULT 'posts';
  ALTER TABLE "_pages_v_rels" ADD COLUMN "courses_id" integer;
  ALTER TABLE "posts_blocks_cta" ADD COLUMN "form_id" integer;
  ALTER TABLE "posts_blocks_content" ADD COLUMN "color_scheme" "enum_posts_blocks_content_color_scheme" DEFAULT 'light';
  ALTER TABLE "posts_blocks_media_block" ADD COLUMN "color_scheme" "enum_posts_blocks_media_block_color_scheme" DEFAULT 'light';
  ALTER TABLE "posts_blocks_archive" ADD COLUMN "color_scheme" "enum_posts_blocks_archive_color_scheme" DEFAULT 'light';
  ALTER TABLE "posts_blocks_form_block" ADD COLUMN "color_scheme" "enum_posts_blocks_form_block_color_scheme" DEFAULT 'light';
  ALTER TABLE "posts_blocks_dynamic_blog_grid" ADD COLUMN "collection_type" "enum_posts_blocks_dynamic_blog_grid_collection_type" DEFAULT 'posts';
  ALTER TABLE "posts_rels" ADD COLUMN "courses_id" integer;
  ALTER TABLE "_posts_v_blocks_cta" ADD COLUMN "form_id" integer;
  ALTER TABLE "_posts_v_blocks_content" ADD COLUMN "color_scheme" "enum__posts_v_blocks_content_color_scheme" DEFAULT 'light';
  ALTER TABLE "_posts_v_blocks_media_block" ADD COLUMN "color_scheme" "enum__posts_v_blocks_media_block_color_scheme" DEFAULT 'light';
  ALTER TABLE "_posts_v_blocks_archive" ADD COLUMN "color_scheme" "enum__posts_v_blocks_archive_color_scheme" DEFAULT 'light';
  ALTER TABLE "_posts_v_blocks_form_block" ADD COLUMN "color_scheme" "enum__posts_v_blocks_form_block_color_scheme" DEFAULT 'light';
  ALTER TABLE "_posts_v_blocks_dynamic_blog_grid" ADD COLUMN "collection_type" "enum__posts_v_blocks_dynamic_blog_grid_collection_type" DEFAULT 'posts';
  ALTER TABLE "_posts_v_rels" ADD COLUMN "courses_id" integer;
  ALTER TABLE "courses_blocks_cta" ADD COLUMN "form_id" integer;
  ALTER TABLE "courses_blocks_content" ADD COLUMN "color_scheme" "enum_courses_blocks_content_color_scheme" DEFAULT 'light';
  ALTER TABLE "courses_blocks_media_block" ADD COLUMN "color_scheme" "enum_courses_blocks_media_block_color_scheme" DEFAULT 'light';
  ALTER TABLE "courses_blocks_archive" ADD COLUMN "color_scheme" "enum_courses_blocks_archive_color_scheme" DEFAULT 'light';
  ALTER TABLE "courses_blocks_form_block" ADD COLUMN "color_scheme" "enum_courses_blocks_form_block_color_scheme" DEFAULT 'light';
  ALTER TABLE "courses_blocks_dynamic_blog_grid" ADD COLUMN "collection_type" "enum_courses_blocks_dynamic_blog_grid_collection_type" DEFAULT 'posts';
  ALTER TABLE "courses_rels" ADD COLUMN "courses_id" integer;
  ALTER TABLE "_courses_v_blocks_cta" ADD COLUMN "form_id" integer;
  ALTER TABLE "_courses_v_blocks_content" ADD COLUMN "color_scheme" "enum__courses_v_blocks_content_color_scheme" DEFAULT 'light';
  ALTER TABLE "_courses_v_blocks_media_block" ADD COLUMN "color_scheme" "enum__courses_v_blocks_media_block_color_scheme" DEFAULT 'light';
  ALTER TABLE "_courses_v_blocks_archive" ADD COLUMN "color_scheme" "enum__courses_v_blocks_archive_color_scheme" DEFAULT 'light';
  ALTER TABLE "_courses_v_blocks_form_block" ADD COLUMN "color_scheme" "enum__courses_v_blocks_form_block_color_scheme" DEFAULT 'light';
  ALTER TABLE "_courses_v_blocks_dynamic_blog_grid" ADD COLUMN "collection_type" "enum__courses_v_blocks_dynamic_blog_grid_collection_type" DEFAULT 'posts';
  ALTER TABLE "_courses_v_rels" ADD COLUMN "courses_id" integer;
  ALTER TABLE "redirects_rels" ADD COLUMN "courses_id" integer;
  ALTER TABLE "search_rels" ADD COLUMN "courses_id" integer;
  ALTER TABLE "header_rels" ADD COLUMN "courses_id" integer;
  ALTER TABLE "footer_rels" ADD COLUMN "courses_id" integer;
  ALTER TABLE "blog_overview_blocks_cta" ADD COLUMN "form_id" integer;
  ALTER TABLE "blog_overview_blocks_content" ADD COLUMN "color_scheme" "enum_blog_overview_blocks_content_color_scheme" DEFAULT 'light' NOT NULL;
  ALTER TABLE "blog_overview_blocks_media_block" ADD COLUMN "color_scheme" "enum_blog_overview_blocks_media_block_color_scheme" DEFAULT 'light' NOT NULL;
  ALTER TABLE "blog_overview_blocks_archive" ADD COLUMN "color_scheme" "enum_blog_overview_blocks_archive_color_scheme" DEFAULT 'light' NOT NULL;
  ALTER TABLE "blog_overview_blocks_form_block" ADD COLUMN "color_scheme" "enum_blog_overview_blocks_form_block_color_scheme" DEFAULT 'light' NOT NULL;
  ALTER TABLE "blog_overview_blocks_dynamic_blog_grid" ADD COLUMN "collection_type" "enum_blog_overview_blocks_dynamic_blog_grid_collection_type" DEFAULT 'posts' NOT NULL;
  ALTER TABLE "blog_overview_rels" ADD COLUMN "courses_id" integer;
  ALTER TABLE "course_overview_blocks_cta" ADD COLUMN "form_id" integer;
  ALTER TABLE "course_overview_blocks_content" ADD COLUMN "color_scheme" "enum_course_overview_blocks_content_color_scheme" DEFAULT 'light' NOT NULL;
  ALTER TABLE "course_overview_blocks_media_block" ADD COLUMN "color_scheme" "enum_course_overview_blocks_media_block_color_scheme" DEFAULT 'light' NOT NULL;
  ALTER TABLE "course_overview_blocks_archive" ADD COLUMN "color_scheme" "enum_course_overview_blocks_archive_color_scheme" DEFAULT 'light' NOT NULL;
  ALTER TABLE "course_overview_blocks_form_block" ADD COLUMN "color_scheme" "enum_course_overview_blocks_form_block_color_scheme" DEFAULT 'light' NOT NULL;
  ALTER TABLE "course_overview_blocks_dynamic_blog_grid" ADD COLUMN "collection_type" "enum_course_overview_blocks_dynamic_blog_grid_collection_type" DEFAULT 'posts' NOT NULL;
  ALTER TABLE "course_overview_rels" ADD COLUMN "courses_id" integer;
  ALTER TABLE "pages_blocks_cta" ADD CONSTRAINT "pages_blocks_cta_form_id_forms_id_fk" FOREIGN KEY ("form_id") REFERENCES "public"."forms"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "pages_rels" ADD CONSTRAINT "pages_rels_courses_fk" FOREIGN KEY ("courses_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_pages_v_blocks_cta" ADD CONSTRAINT "_pages_v_blocks_cta_form_id_forms_id_fk" FOREIGN KEY ("form_id") REFERENCES "public"."forms"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_pages_v_rels" ADD CONSTRAINT "_pages_v_rels_courses_fk" FOREIGN KEY ("courses_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "posts_blocks_cta" ADD CONSTRAINT "posts_blocks_cta_form_id_forms_id_fk" FOREIGN KEY ("form_id") REFERENCES "public"."forms"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "posts_rels" ADD CONSTRAINT "posts_rels_courses_fk" FOREIGN KEY ("courses_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_posts_v_blocks_cta" ADD CONSTRAINT "_posts_v_blocks_cta_form_id_forms_id_fk" FOREIGN KEY ("form_id") REFERENCES "public"."forms"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_posts_v_rels" ADD CONSTRAINT "_posts_v_rels_courses_fk" FOREIGN KEY ("courses_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "courses_blocks_cta" ADD CONSTRAINT "courses_blocks_cta_form_id_forms_id_fk" FOREIGN KEY ("form_id") REFERENCES "public"."forms"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "courses_rels" ADD CONSTRAINT "courses_rels_courses_fk" FOREIGN KEY ("courses_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "_courses_v_blocks_cta" ADD CONSTRAINT "_courses_v_blocks_cta_form_id_forms_id_fk" FOREIGN KEY ("form_id") REFERENCES "public"."forms"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "_courses_v_rels" ADD CONSTRAINT "_courses_v_rels_courses_fk" FOREIGN KEY ("courses_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "redirects_rels" ADD CONSTRAINT "redirects_rels_courses_fk" FOREIGN KEY ("courses_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "search_rels" ADD CONSTRAINT "search_rels_courses_fk" FOREIGN KEY ("courses_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "header_rels" ADD CONSTRAINT "header_rels_courses_fk" FOREIGN KEY ("courses_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "footer_rels" ADD CONSTRAINT "footer_rels_courses_fk" FOREIGN KEY ("courses_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "blog_overview_blocks_cta" ADD CONSTRAINT "blog_overview_blocks_cta_form_id_forms_id_fk" FOREIGN KEY ("form_id") REFERENCES "public"."forms"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "blog_overview_rels" ADD CONSTRAINT "blog_overview_rels_courses_fk" FOREIGN KEY ("courses_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "course_overview_blocks_cta" ADD CONSTRAINT "course_overview_blocks_cta_form_id_forms_id_fk" FOREIGN KEY ("form_id") REFERENCES "public"."forms"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "course_overview_rels" ADD CONSTRAINT "course_overview_rels_courses_fk" FOREIGN KEY ("courses_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "pages_blocks_cta_form_idx" ON "pages_blocks_cta" USING btree ("form_id");
  CREATE INDEX "pages_rels_courses_id_idx" ON "pages_rels" USING btree ("courses_id");
  CREATE INDEX "_pages_v_blocks_cta_form_idx" ON "_pages_v_blocks_cta" USING btree ("form_id");
  CREATE INDEX "_pages_v_rels_courses_id_idx" ON "_pages_v_rels" USING btree ("courses_id");
  CREATE INDEX "posts_blocks_cta_form_idx" ON "posts_blocks_cta" USING btree ("form_id");
  CREATE INDEX "posts_rels_courses_id_idx" ON "posts_rels" USING btree ("courses_id");
  CREATE INDEX "_posts_v_blocks_cta_form_idx" ON "_posts_v_blocks_cta" USING btree ("form_id");
  CREATE INDEX "_posts_v_rels_courses_id_idx" ON "_posts_v_rels" USING btree ("courses_id");
  CREATE INDEX "courses_blocks_cta_form_idx" ON "courses_blocks_cta" USING btree ("form_id");
  CREATE INDEX "courses_rels_courses_id_idx" ON "courses_rels" USING btree ("courses_id");
  CREATE INDEX "_courses_v_blocks_cta_form_idx" ON "_courses_v_blocks_cta" USING btree ("form_id");
  CREATE INDEX "_courses_v_rels_courses_id_idx" ON "_courses_v_rels" USING btree ("courses_id");
  CREATE INDEX "redirects_rels_courses_id_idx" ON "redirects_rels" USING btree ("courses_id");
  CREATE INDEX "search_rels_courses_id_idx" ON "search_rels" USING btree ("courses_id");
  CREATE INDEX "header_rels_courses_id_idx" ON "header_rels" USING btree ("courses_id");
  CREATE INDEX "footer_rels_courses_id_idx" ON "footer_rels" USING btree ("courses_id");
  CREATE INDEX "blog_overview_blocks_cta_form_idx" ON "blog_overview_blocks_cta" USING btree ("form_id");
  CREATE INDEX "blog_overview_rels_courses_id_idx" ON "blog_overview_rels" USING btree ("courses_id");
  CREATE INDEX "course_overview_blocks_cta_form_idx" ON "course_overview_blocks_cta" USING btree ("form_id");
  CREATE INDEX "course_overview_rels_courses_id_idx" ON "course_overview_rels" USING btree ("courses_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_cta" DROP CONSTRAINT "pages_blocks_cta_form_id_forms_id_fk";
  
  ALTER TABLE "pages_rels" DROP CONSTRAINT "pages_rels_courses_fk";
  
  ALTER TABLE "_pages_v_blocks_cta" DROP CONSTRAINT "_pages_v_blocks_cta_form_id_forms_id_fk";
  
  ALTER TABLE "_pages_v_rels" DROP CONSTRAINT "_pages_v_rels_courses_fk";
  
  ALTER TABLE "posts_blocks_cta" DROP CONSTRAINT "posts_blocks_cta_form_id_forms_id_fk";
  
  ALTER TABLE "posts_rels" DROP CONSTRAINT "posts_rels_courses_fk";
  
  ALTER TABLE "_posts_v_blocks_cta" DROP CONSTRAINT "_posts_v_blocks_cta_form_id_forms_id_fk";
  
  ALTER TABLE "_posts_v_rels" DROP CONSTRAINT "_posts_v_rels_courses_fk";
  
  ALTER TABLE "courses_blocks_cta" DROP CONSTRAINT "courses_blocks_cta_form_id_forms_id_fk";
  
  ALTER TABLE "courses_rels" DROP CONSTRAINT "courses_rels_courses_fk";
  
  ALTER TABLE "_courses_v_blocks_cta" DROP CONSTRAINT "_courses_v_blocks_cta_form_id_forms_id_fk";
  
  ALTER TABLE "_courses_v_rels" DROP CONSTRAINT "_courses_v_rels_courses_fk";
  
  ALTER TABLE "redirects_rels" DROP CONSTRAINT "redirects_rels_courses_fk";
  
  ALTER TABLE "search_rels" DROP CONSTRAINT "search_rels_courses_fk";
  
  ALTER TABLE "header_rels" DROP CONSTRAINT "header_rels_courses_fk";
  
  ALTER TABLE "footer_rels" DROP CONSTRAINT "footer_rels_courses_fk";
  
  ALTER TABLE "blog_overview_blocks_cta" DROP CONSTRAINT "blog_overview_blocks_cta_form_id_forms_id_fk";
  
  ALTER TABLE "blog_overview_rels" DROP CONSTRAINT "blog_overview_rels_courses_fk";
  
  ALTER TABLE "course_overview_blocks_cta" DROP CONSTRAINT "course_overview_blocks_cta_form_id_forms_id_fk";
  
  ALTER TABLE "course_overview_rels" DROP CONSTRAINT "course_overview_rels_courses_fk";
  
  DROP INDEX "pages_blocks_cta_form_idx";
  DROP INDEX "pages_rels_courses_id_idx";
  DROP INDEX "_pages_v_blocks_cta_form_idx";
  DROP INDEX "_pages_v_rels_courses_id_idx";
  DROP INDEX "posts_blocks_cta_form_idx";
  DROP INDEX "posts_rels_courses_id_idx";
  DROP INDEX "_posts_v_blocks_cta_form_idx";
  DROP INDEX "_posts_v_rels_courses_id_idx";
  DROP INDEX "courses_blocks_cta_form_idx";
  DROP INDEX "courses_rels_courses_id_idx";
  DROP INDEX "_courses_v_blocks_cta_form_idx";
  DROP INDEX "_courses_v_rels_courses_id_idx";
  DROP INDEX "redirects_rels_courses_id_idx";
  DROP INDEX "search_rels_courses_id_idx";
  DROP INDEX "header_rels_courses_id_idx";
  DROP INDEX "footer_rels_courses_id_idx";
  DROP INDEX "blog_overview_blocks_cta_form_idx";
  DROP INDEX "blog_overview_rels_courses_id_idx";
  DROP INDEX "course_overview_blocks_cta_form_idx";
  DROP INDEX "course_overview_rels_courses_id_idx";
  ALTER TABLE "pages_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'default';
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "pages_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'By clicking Sign Up you''re confirming that you agree with our Terms and Conditions.';
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "rich_text" DROP DEFAULT;
  ALTER TABLE "pages_blocks_archive" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "pages_blocks_form_block" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "pages_blocks_faq" ALTER COLUMN "contact_section_contact_description" DROP DEFAULT;
  ALTER TABLE "pages_blocks_team" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "pages_blocks_team" ALTER COLUMN "hiring_section_hiring_description" DROP DEFAULT;
  ALTER TABLE "pages_blocks_testimonials" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "pages_blocks_pricing_table" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "pages_blocks_two_column_layout" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "pages_blocks_feature_grid" ALTER COLUMN "header_section_description" DROP DEFAULT;
  ALTER TABLE "pages_blocks_header" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "pages_blocks_gallery" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "pages_blocks_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "pages_blocks_dynamic_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "pages" ALTER COLUMN "hero_rich_text" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'default';
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'By clicking Sign Up you''re confirming that you agree with our Terms and Conditions.';
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "rich_text" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_archive" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_form_block" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_faq" ALTER COLUMN "contact_section_contact_description" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_team" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_team" ALTER COLUMN "hiring_section_hiring_description" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_testimonials" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_pricing_table" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_two_column_layout" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_feature_grid" ALTER COLUMN "header_section_description" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_header" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_gallery" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_pages_v_blocks_dynamic_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_pages_v" ALTER COLUMN "version_hero_rich_text" DROP DEFAULT;
  ALTER TABLE "posts_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'default';
  ALTER TABLE "posts_blocks_cta" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "posts_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'By clicking Sign Up you''re confirming that you agree with our Terms and Conditions.';
  ALTER TABLE "posts_blocks_content_columns" ALTER COLUMN "rich_text" DROP DEFAULT;
  ALTER TABLE "posts_blocks_archive" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "posts_blocks_form_block" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "posts_blocks_faq" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "posts_blocks_faq" ALTER COLUMN "contact_section_contact_description" DROP DEFAULT;
  ALTER TABLE "posts_blocks_team" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "posts_blocks_team" ALTER COLUMN "hiring_section_hiring_description" DROP DEFAULT;
  ALTER TABLE "posts_blocks_testimonials" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "posts_blocks_pricing_table" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "posts_blocks_two_column_layout" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "posts_blocks_feature_grid" ALTER COLUMN "header_section_description" DROP DEFAULT;
  ALTER TABLE "posts_blocks_header" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "posts_blocks_gallery" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "posts_blocks_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "posts_blocks_dynamic_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'default';
  ALTER TABLE "_posts_v_blocks_cta" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'By clicking Sign Up you''re confirming that you agree with our Terms and Conditions.';
  ALTER TABLE "_posts_v_blocks_content_columns" ALTER COLUMN "rich_text" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_archive" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_form_block" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_faq" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_faq" ALTER COLUMN "contact_section_contact_description" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_team" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_team" ALTER COLUMN "hiring_section_hiring_description" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_testimonials" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_pricing_table" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_two_column_layout" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_feature_grid" ALTER COLUMN "header_section_description" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_header" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_gallery" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_posts_v_blocks_dynamic_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "courses_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'default';
  ALTER TABLE "courses_blocks_cta" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "courses_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'By clicking Sign Up you''re confirming that you agree with our Terms and Conditions.';
  ALTER TABLE "courses_blocks_content_columns" ALTER COLUMN "rich_text" DROP DEFAULT;
  ALTER TABLE "courses_blocks_archive" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "courses_blocks_form_block" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "courses_blocks_faq" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "courses_blocks_faq" ALTER COLUMN "contact_section_contact_description" DROP DEFAULT;
  ALTER TABLE "courses_blocks_team" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "courses_blocks_team" ALTER COLUMN "hiring_section_hiring_description" DROP DEFAULT;
  ALTER TABLE "courses_blocks_testimonials" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "courses_blocks_pricing_table" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "courses_blocks_two_column_layout" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "courses_blocks_feature_grid" ALTER COLUMN "header_section_description" DROP DEFAULT;
  ALTER TABLE "courses_blocks_header" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "courses_blocks_gallery" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "courses_blocks_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "courses_blocks_dynamic_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'default';
  ALTER TABLE "_courses_v_blocks_cta" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'By clicking Sign Up you''re confirming that you agree with our Terms and Conditions.';
  ALTER TABLE "_courses_v_blocks_content_columns" ALTER COLUMN "rich_text" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_archive" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_form_block" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_faq" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_faq" ALTER COLUMN "contact_section_contact_description" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_team" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_team" ALTER COLUMN "hiring_section_hiring_description" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_testimonials" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_pricing_table" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_two_column_layout" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_feature_grid" ALTER COLUMN "header_section_description" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_header" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_gallery" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "_courses_v_blocks_dynamic_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "global_cta" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'default';
  ALTER TABLE "blog_overview_blocks_cta" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'By clicking Sign Up you''re confirming that you agree with our Terms and Conditions.';
  ALTER TABLE "blog_overview_blocks_content_columns" ALTER COLUMN "rich_text" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_archive" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_form_block" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_faq" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_faq" ALTER COLUMN "contact_section_contact_description" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_team" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_team" ALTER COLUMN "hiring_section_hiring_description" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_testimonials" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_pricing_table" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_two_column_layout" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_feature_grid" ALTER COLUMN "header_section_description" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_header" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_gallery" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "blog_overview_blocks_dynamic_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_cta_buttons" ALTER COLUMN "variant" SET DEFAULT 'default';
  ALTER TABLE "course_overview_blocks_cta" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_cta" ALTER COLUMN "form_settings_terms_text" SET DEFAULT 'By clicking Sign Up you''re confirming that you agree with our Terms and Conditions.';
  ALTER TABLE "course_overview_blocks_content_columns" ALTER COLUMN "rich_text" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_archive" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_form_block" ALTER COLUMN "intro_content" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_faq" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_faq" ALTER COLUMN "contact_section_contact_description" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_team" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_team" ALTER COLUMN "hiring_section_hiring_description" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_testimonials" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_pricing_table" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_two_column_layout" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_feature_grid" ALTER COLUMN "header_section_description" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_header" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_gallery" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "course_overview_blocks_dynamic_blog_grid" ALTER COLUMN "description" DROP DEFAULT;
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "form_id";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "color_scheme";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "color_scheme";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "color_scheme";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "color_scheme";
  ALTER TABLE "pages_blocks_dynamic_blog_grid" DROP COLUMN "collection_type";
  ALTER TABLE "pages_rels" DROP COLUMN "courses_id";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "form_id";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "color_scheme";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "color_scheme";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "color_scheme";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "color_scheme";
  ALTER TABLE "_pages_v_blocks_dynamic_blog_grid" DROP COLUMN "collection_type";
  ALTER TABLE "_pages_v_rels" DROP COLUMN "courses_id";
  ALTER TABLE "posts_blocks_cta" DROP COLUMN "form_id";
  ALTER TABLE "posts_blocks_content" DROP COLUMN "color_scheme";
  ALTER TABLE "posts_blocks_media_block" DROP COLUMN "color_scheme";
  ALTER TABLE "posts_blocks_archive" DROP COLUMN "color_scheme";
  ALTER TABLE "posts_blocks_form_block" DROP COLUMN "color_scheme";
  ALTER TABLE "posts_blocks_dynamic_blog_grid" DROP COLUMN "collection_type";
  ALTER TABLE "posts_rels" DROP COLUMN "courses_id";
  ALTER TABLE "_posts_v_blocks_cta" DROP COLUMN "form_id";
  ALTER TABLE "_posts_v_blocks_content" DROP COLUMN "color_scheme";
  ALTER TABLE "_posts_v_blocks_media_block" DROP COLUMN "color_scheme";
  ALTER TABLE "_posts_v_blocks_archive" DROP COLUMN "color_scheme";
  ALTER TABLE "_posts_v_blocks_form_block" DROP COLUMN "color_scheme";
  ALTER TABLE "_posts_v_blocks_dynamic_blog_grid" DROP COLUMN "collection_type";
  ALTER TABLE "_posts_v_rels" DROP COLUMN "courses_id";
  ALTER TABLE "courses_blocks_cta" DROP COLUMN "form_id";
  ALTER TABLE "courses_blocks_content" DROP COLUMN "color_scheme";
  ALTER TABLE "courses_blocks_media_block" DROP COLUMN "color_scheme";
  ALTER TABLE "courses_blocks_archive" DROP COLUMN "color_scheme";
  ALTER TABLE "courses_blocks_form_block" DROP COLUMN "color_scheme";
  ALTER TABLE "courses_blocks_dynamic_blog_grid" DROP COLUMN "collection_type";
  ALTER TABLE "courses_rels" DROP COLUMN "courses_id";
  ALTER TABLE "_courses_v_blocks_cta" DROP COLUMN "form_id";
  ALTER TABLE "_courses_v_blocks_content" DROP COLUMN "color_scheme";
  ALTER TABLE "_courses_v_blocks_media_block" DROP COLUMN "color_scheme";
  ALTER TABLE "_courses_v_blocks_archive" DROP COLUMN "color_scheme";
  ALTER TABLE "_courses_v_blocks_form_block" DROP COLUMN "color_scheme";
  ALTER TABLE "_courses_v_blocks_dynamic_blog_grid" DROP COLUMN "collection_type";
  ALTER TABLE "_courses_v_rels" DROP COLUMN "courses_id";
  ALTER TABLE "redirects_rels" DROP COLUMN "courses_id";
  ALTER TABLE "search_rels" DROP COLUMN "courses_id";
  ALTER TABLE "header_rels" DROP COLUMN "courses_id";
  ALTER TABLE "footer_rels" DROP COLUMN "courses_id";
  ALTER TABLE "blog_overview_blocks_cta" DROP COLUMN "form_id";
  ALTER TABLE "blog_overview_blocks_content" DROP COLUMN "color_scheme";
  ALTER TABLE "blog_overview_blocks_media_block" DROP COLUMN "color_scheme";
  ALTER TABLE "blog_overview_blocks_archive" DROP COLUMN "color_scheme";
  ALTER TABLE "blog_overview_blocks_form_block" DROP COLUMN "color_scheme";
  ALTER TABLE "blog_overview_blocks_dynamic_blog_grid" DROP COLUMN "collection_type";
  ALTER TABLE "blog_overview_rels" DROP COLUMN "courses_id";
  ALTER TABLE "course_overview_blocks_cta" DROP COLUMN "form_id";
  ALTER TABLE "course_overview_blocks_content" DROP COLUMN "color_scheme";
  ALTER TABLE "course_overview_blocks_media_block" DROP COLUMN "color_scheme";
  ALTER TABLE "course_overview_blocks_archive" DROP COLUMN "color_scheme";
  ALTER TABLE "course_overview_blocks_form_block" DROP COLUMN "color_scheme";
  ALTER TABLE "course_overview_blocks_dynamic_blog_grid" DROP COLUMN "collection_type";
  ALTER TABLE "course_overview_rels" DROP COLUMN "courses_id";
  DROP TYPE "public"."enum_pages_blocks_content_color_scheme";
  DROP TYPE "public"."enum_pages_blocks_media_block_color_scheme";
  DROP TYPE "public"."enum_pages_blocks_archive_color_scheme";
  DROP TYPE "public"."enum_pages_blocks_form_block_color_scheme";
  DROP TYPE "public"."enum_pages_blocks_dynamic_blog_grid_collection_type";
  DROP TYPE "public"."enum__pages_v_blocks_content_color_scheme";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_color_scheme";
  DROP TYPE "public"."enum__pages_v_blocks_archive_color_scheme";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_color_scheme";
  DROP TYPE "public"."enum__pages_v_blocks_dynamic_blog_grid_collection_type";
  DROP TYPE "public"."enum_posts_blocks_content_color_scheme";
  DROP TYPE "public"."enum_posts_blocks_media_block_color_scheme";
  DROP TYPE "public"."enum_posts_blocks_archive_color_scheme";
  DROP TYPE "public"."enum_posts_blocks_form_block_color_scheme";
  DROP TYPE "public"."enum_posts_blocks_dynamic_blog_grid_collection_type";
  DROP TYPE "public"."enum__posts_v_blocks_content_color_scheme";
  DROP TYPE "public"."enum__posts_v_blocks_media_block_color_scheme";
  DROP TYPE "public"."enum__posts_v_blocks_archive_color_scheme";
  DROP TYPE "public"."enum__posts_v_blocks_form_block_color_scheme";
  DROP TYPE "public"."enum__posts_v_blocks_dynamic_blog_grid_collection_type";
  DROP TYPE "public"."enum_courses_blocks_content_color_scheme";
  DROP TYPE "public"."enum_courses_blocks_media_block_color_scheme";
  DROP TYPE "public"."enum_courses_blocks_archive_color_scheme";
  DROP TYPE "public"."enum_courses_blocks_form_block_color_scheme";
  DROP TYPE "public"."enum_courses_blocks_dynamic_blog_grid_collection_type";
  DROP TYPE "public"."enum__courses_v_blocks_content_color_scheme";
  DROP TYPE "public"."enum__courses_v_blocks_media_block_color_scheme";
  DROP TYPE "public"."enum__courses_v_blocks_archive_color_scheme";
  DROP TYPE "public"."enum__courses_v_blocks_form_block_color_scheme";
  DROP TYPE "public"."enum__courses_v_blocks_dynamic_blog_grid_collection_type";
  DROP TYPE "public"."enum_blog_overview_blocks_content_color_scheme";
  DROP TYPE "public"."enum_blog_overview_blocks_media_block_color_scheme";
  DROP TYPE "public"."enum_blog_overview_blocks_archive_color_scheme";
  DROP TYPE "public"."enum_blog_overview_blocks_form_block_color_scheme";
  DROP TYPE "public"."enum_blog_overview_blocks_dynamic_blog_grid_collection_type";
  DROP TYPE "public"."enum_course_overview_blocks_content_color_scheme";
  DROP TYPE "public"."enum_course_overview_blocks_media_block_color_scheme";
  DROP TYPE "public"."enum_course_overview_blocks_archive_color_scheme";
  DROP TYPE "public"."enum_course_overview_blocks_form_block_color_scheme";
  DROP TYPE "public"."enum_course_overview_blocks_dynamic_blog_grid_collection_type";`)
}
